### ISSUE TITLE
Couldn't connect to MySQL server when restarting docker

### ISSUE THREAD

**Issue by acaciochinato** [frauhottelmann/daloradius-docker#9]
Hello! 

I don't know if this is really a issue or just a bad deploy from my part, but when I need to restart the docker engine or the host machine, the radius docker can't reconnect to mysql database upon restart, issuing this error in the logs:

```
rlm_sql (sql): Opening additional connection (0), 1 of 32 pending slots used
rlm_sql_mysql: Starting connect to MySQL server
rlm_sql_mysql: Couldn't connect to MySQL server radius@radius-mysql:radius
rlm_sql_mysql: MySQL error: Can't connect to MySQL server on 'radius-mysql' (111)
rlm_sql_mysql: Socket destructor called, closing socket
rlm_sql (sql): Opening connection failed (0)
rlm_sql (sql): Removing connection pool
/etc/freeradius/3.0/mods-enabled/sql[27]: Instantiation failed for module "sql"
<b>Database connection error</b><br/>
            <b>Error Message</b>: DB Error: connect failed<br/><b>Debug</b>:  [nativecode=Connection refused]]
```

If I restart only the container or deploying it again, it works normally.

Here is my docker file:

```
version: "3"
services:
  radius-mysql:
    image: mariadb:10.3
    container_name: radius-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=*****
      - MYSQL_ROOT_PASSWORD=*****
      - TZ=America/Sao_Paulo
    volumes:
      - "/docker/radius-mysql:/var/lib/mysql"
    deploy:
      resources:
       limits:
        memory: 1024M
  radius:
    image: frauhottelmann/daloradius-docker:v1.1-4
    container_name: radius
    restart: unless-stopped
    depends_on:
      - "radius-mysql" 
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
      - '80:80'
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=*****
      - TZ=America/Sao_Paulo
    volumes:
     - /docker/radius/mods-available/eap:/etc/freeradius/3.0/mods-available/eap
     - /docker/radius/certs:/etc/freeradius/3.0/certs
```
